version: 2.1
jobs:
  build_image:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: build docker image
          command: |
            docker build --tag=rab7a:${CIRCLE_BUILD_NUM} .

workflows:
  docker:
    jobs:
      - build_image